version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

  app:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/rdx_project
      - JWT_SECRET=dev_secret
      - FILE_TOKEN_SECRET=file_secret_dev
    depends_on:
      - mongo

volumes:
  mongo-data:
